### ISSUE TITLE
Instantiation of varfont

### ISSUE THREAD

**Issue by chrissimpkins** [laerm0/opensans#8] opened 2019-05-03 03:51 UTC
I took a look at the fonts on the path https://github.com/laerm0/opensans/blob/quad_UFOs/source/quadratic/variable_ttf/ and it appears that there is a problem with the font https://github.com/laerm0/opensans/blob/quad_UFOs/source/quadratic/variable_ttf/OpenSans-Roman-quadratic-VF.ttf (top image).  When you view it in Axis Praxis and FontView the weights are only reflected in a few of the glyphs.  The rest remain at the 300 weight irrespective of the definition when you create instances or use sliders in the VF viewers.

When I build instances with `https://github.com/laerm0/opensans/blob/quad_UFOs/source/quadratic/variable_ttf/OpenSans-Roman-quadratic-VF copy.ttf`, the weight information translates into the instances appropriately, but the width does not for some reason (see other views in images below).  I can confirm that the width axis works for this font with the VF viewer sliders.  

<img width="696" alt="m8bcc-image" src="https://user-images.githubusercontent.com/4249591/57118956-9cecc380-6d34-11e9-8652-202340cad296.png">

I don't know why this is the case.  I built directly with `fonttools varLib.mutator` and this was the output that I get using the verbose setting (and with no relevant OT table diff c/w the builds that came from the vf2s.py script):

```
$ fonttools varLib.mutator --verbose -o test40060.ttf OpenSans-Roman-quadratic-VF-copy.ttf wght=400 wdth=60

Location: {'wght': 400.0, 'wdth': 60.0}
Loading variable font
Reading 'fvar' table from disk
Decompiling 'fvar' table
Reading 'avar' table from disk
Decompiling 'avar' table
Normalized location: {'wght': 0.23333740234375, 'wdth': 0.0}
Mutating glyf/gvar tables
Reading 'gvar' table from disk
Decompiling 'gvar' table
Reading 'post' table from disk
Decompiling 'post' table
Reading 'maxp' table from disk
Decompiling 'maxp' table
Reading 'glyf' table from disk
Decompiling 'glyf' table
Reading 'loca' table from disk
Decompiling 'loca' table
Reading 'head' table from disk
Decompiling 'head' table
Reading 'hmtx' table from disk
Decompiling 'hmtx' table
Reading 'hhea' table from disk
Decompiling 'hhea' table
Mutating MVAR table
Reading 'MVAR' table from disk
Decompiling 'MVAR' table
Reading 'OS/2' table from disk
Decompiling 'OS/2' table
Mutating FeatureVariations
Reading 'GSUB' table from disk
Decompiling 'GSUB' table
Reading 'GPOS' table from disk
Decompiling 'GPOS' table
Reading 'GDEF' table from disk
Decompiling 'GDEF' table
Mutating GDEF/GPOS/GSUB tables
Pruning name table
Reading 'name' table from disk
Decompiling 'name' table
Removing variable tables
Saving instance font test40060.ttf
compiling 'glyf' table
writing 'glyf' table to disk
compiling 'maxp' table
writing 'maxp' table to disk
compiling 'loca' table
writing 'loca' table to disk
compiling 'head' table
writing 'head' table to disk
compiling 'hmtx' table
writing 'hmtx' table to disk
compiling 'hhea' table
writing 'hhea' table to disk
compiling 'OS/2' table
Reading 'cmap' table from disk
Decompiling 'cmap' table
writing 'OS/2' table to disk
compiling 'cmap' table
writing 'cmap' table to disk
compiling 'name' table
writing 'name' table to disk
compiling 'post' table
writing 'post' table to disk
compiling 'GDEF' table
writing 'GDEF' table to disk
compiling 'GPOS' table
writing 'GPOS' table to disk
compiling 'GSUB' table
writing 'GSUB' table to disk
```

Built with fontTools v3.40.0.  This sounds like an issue for the fontTools repository.  Unfortunately, I don't know how to troubleshoot it further.  Sorry...

**Comment by laerm0** [comment] 2019-05-03 14:02
Huh. Strange. Okay, thanks @chrissimpkins !

**Comment by chrissimpkins** [comment] 2019-05-03 14:19
What was the difference in the build process between those two VF files?

**Comment by laerm0** [comment] 2019-05-03 14:23
(ah, I was just about to post) 

The `copy` is an oooold file I made for testing that doesn't have a proper `wdth` axis (I really should delete it from the repo). 

It looks like the issue is with `cu2qu` somewhere. If I build the TTF using the designspace and not running `python3 -m cu2qu -i` on the UFOs, it builds fine and works in axis-praxis. If I do send them through `cu2qu`, they break. I don't think it's a `cu2qu` thing so much as it is some package it relies on has changed. I'll dig in to that and talk to Cosimo.

Thanks!

**Comment by anthrotype** [comment] 2019-05-03 14:28
can you please tell me exactly how to reproduce this?

**Comment by laerm0** [comment] 2019-05-03 14:33
I'm working on it; I'll let you know when I have a better idea. If you want to follow along:

1. clone this repo
2. switch to the `quad_UFOs` branch
3. export UFOs from `source/OpenSans-Roman.glyphs`
4. rename to remove spaces: `:; for I in *.ufo; do mv "${I}" "${I// /}"; done`
5. cu2qu: `:; for I in *.ufo; do python3 -m cu2qu -i "${I}"; done`
6. fontmake: ` fontmake -m ../../OpenSans-Roman-quadratic.designspace -o variable`

**Comment by laerm0** [comment] 2019-05-03 14:35
I am looking at the quad UFOs now and it looks like it gave them the same start points but different numbers of points.

I updated all my packages in the venv yesterday and that's when something went awry. I think it was something that `cu2qu` depends on. I had some errors when `pycairo` tried to update itself, but I don't think that would be a dependency of `cu2qu`.

**Comment by anthrotype** [comment] 2019-05-03 14:38
cu2qu doesn't have dependencies besides fonttools, but nothing critical has changed.
When you ask --interpolatable, cu2qu will error out if outlines are not compatible.

**Comment by laerm0** [comment] 2019-05-03 14:39
Strange. Let me research further. Thanks @anthrotype.

**Comment by anthrotype** [comment] 2019-05-03 14:43
how do you export from Glyphs to UFOs?

if I do:

fontmake -g source/OpenSans-Roman.glyphs -o ufo

from your quad_UFOs branch, I get the usual error about multi-axes bracket layers unsupported by glyphsLib.

I would not recommend that you use Glyphs.app own UFO export feature, it is not as reliable as glyphsLib.

**Comment by laerm0** [comment] 2019-05-03 15:47
> I would not recommend that you use Glyphs.app own UFO export feature, it is not as reliable as glyphsLib.

Well, I guess I know that now. 🙄

I'll have to get back to you on this.

**Comment by laerm0** [comment] 2019-05-03 16:33
_note:_ I've merged `quad_UFOs` into `master` as quadratics are the way forward here.

**Comment by anthrotype** [comment] 2019-05-03 16:36
so is there an issue or not? i'm confused

**Comment by laerm0** [comment] 2019-05-03 16:40
Here or in the issue I filed on fontmake/548? Here remains to be seen; fontmake/548 is asking for clarification.

**Comment by laerm0** [comment] 2019-08-23 18:37
Closing as solved and cleaned up.

**Closed by laerm0** 2019-08-23 18:37 UTC
